// Generates web/data.js from the canonical sources so the web app reuses the
// same lock history and translations as the CLI/TUI — no hand-copying.
//
//   node web/build-data.mjs   (run from the repo root; the Pages workflow runs it too)

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Display names for each language code (mirrors LANGUAGES in src/tui.rs).
const LANG_NAMES = {
  en: "English",
  pl: "Polski",
  de: "Deutsch",
  ru: "Русский",
  uk: "Українська",
  es: "Español",
  pt: "Português",
  fr: "Français",
};
// Keep English first (it's the fallback), then the rest in registration order.
const LANG_ORDER = ["en", "pl", "de", "ru", "uk", "es", "pt", "fr"];

function parseCatalog(src) {
  const map = {};
  for (const raw of src.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("=");
    if (i < 0) continue;
    map[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return map;
}

function buildI18n() {
  const i18n = {};
  const langs = [];
  const codes = readdirSync(join(root, "src/i18n"))
    .filter((f) => f.endsWith(".txt"))
    .map((f) => f.replace(/\.txt$/, ""));
  for (const code of LANG_ORDER) {
    if (!codes.includes(code)) continue;
    i18n[code] = parseCatalog(readFileSync(join(root, "src/i18n", `${code}.txt`), "utf8"));
    langs.push({ code, name: LANG_NAMES[code] ?? code });
  }
  return { i18n, langs };
}

// Mirror of parse_history in src/lib.rs: split on "## " headers, then read the
// Rules fence, Start line, and Solution fence in each section.
function fenceAfter(lines, from) {
  let j = from;
  while (j < lines.length && lines[j].trim() !== "```") j++;
  if (j >= lines.length) return null;
  j++;
  const out = [];
  while (j < lines.length && lines[j].trim() !== "```") out.push(lines[j++]);
  return out;
}

function parseIntArray(s) {
  const l = s.indexOf("["), r = s.indexOf("]");
  if (l < 0 || r < 0) return null;
  const parts = s
    .slice(l + 1, r)
    .split(",")
    .map((x) => x.trim())
    .filter((x) => x !== "")
    .map(Number);
  return parts.length > 0 && parts.every(Number.isFinite) ? parts : null;
}

function parseHistory(text) {
  const lines = text.split("\n");
  const starts = [];
  lines.forEach((l, i) => l.startsWith("## ") && starts.push(i));
  const locks = [];
  starts.forEach((s, k) => {
    const end = k + 1 < starts.length ? starts[k + 1] : lines.length;
    const body = lines.slice(s + 1, end);
    const name = lines[s].slice(3).trim();
    let start = null;
    let solution = [];

    // Collect numbered rule lines; the tumbler count N is inferred (2..8), not
    // fixed at 6 — mirrors rules_from_pairs in src/lib.rs.
    const rulePairs = [];
    const ri = body.findIndex((l) => l.includes("**Rules"));
    if (ri >= 0) {
      for (const line of fenceAfter(body, ri) ?? []) {
        const c = line.indexOf(":");
        if (c < 0) continue;
        const n = Number(line.slice(0, c).trim());
        if (Number.isInteger(n)) rulePairs.push([n, line.slice(c + 1).trim()]);
      }
    }
    const si = body.findIndex((l) => l.includes("**Start"));
    if (si >= 0) start = parseIntArray(body[si]);
    const soli = body.findIndex((l) => l.includes("**Solution"));
    if (soli >= 0) {
      const content = fenceAfter(body, soli);
      if (content) solution = content.filter((l) => l.trim() !== "");
    }

    const maxIdx = rulePairs.reduce((m, [i]) => Math.max(m, i), 0);
    const n = Math.max(maxIdx, start ? start.length : 0);
    const rules = Array(n).fill("");
    for (const [i, t] of rulePairs) if (i >= 1 && i <= n) rules[i - 1] = t;

    locks.push({ name, rules, start, solution });
  });
  return locks;
}

const { i18n, langs } = buildI18n();
const history = parseHistory(readFileSync(join(root, "history-of-locks.md"), "utf8"));

const out =
  "// AUTO-GENERATED by web/build-data.mjs — do not edit by hand.\n" +
  `export const LANGS = ${JSON.stringify(langs)};\n` +
  `export const I18N = ${JSON.stringify(i18n)};\n` +
  `export const HISTORY = ${JSON.stringify(history)};\n`;

writeFileSync(join(root, "web/data.js"), out);
console.log(
  `web/data.js: ${langs.length} languages, ${history.length} locks, ` +
    `${Object.keys(i18n.en).length} keys`
);
